import { ArrowRight, Blocks, Bot, Check, CheckCircle2, ChevronRight, Code2, Facebook, Globe2, HeartPulse, Instagram, LoaderCircle, Menu, Pill, Play, Rocket, Scissors, Send, Sparkles, Target, X, Youtube, Zap } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { submitWebsiteLead } from "./leadService";
import { socialLinks as staticSocialLinks } from "./socials";
import { getPublicSiteSettings, type PublicSiteSettings } from "./siteSettings";

type Language = "es" | "en";
const copy = {
  es: {
    nav:["Servicios","Proceso","Nosotros"],talk:"Hablemos",menu:["Abrir menú","Cerrar menú"],eyebrow:"Tecnología para negocios de frontera",heroA:"Haz que te encuentren",heroB:"antes de cruzar.",heroText:"Creamos experiencias digitales bilingües para negocios de Nuevo Progreso que reciben clientes de México y Estados Unidos.",start:"Quiero empezar",discover:"Descubre cómo",proofs:["Español + English","Diseño que genera confianza","Atención cercana"],visualLabel:"Representación de una experiencia digital bilingüe",miniTop:"TU NEGOCIO, SIN FRONTERAS",miniTitle:["Confianza que comienza","antes de la visita."],miniButton:"Reservar una cita",performance:"Rendimiento",focus:"Enfoque",results:"Resultados",
    servicesKicker:"CREADO PARA NEGOCIOS LOCALES",servicesTitle:["Convierte búsquedas en","nuevos clientes."],servicesIntro:"Ayudamos a dentistas, spas, salones, farmacias y comercios de la frontera a verse profesionales, responder dudas y facilitar la visita.",services:[["Presencia bilingüe","Un sitio claro en español e inglés para generar confianza antes de que el visitante llegue."],["Reservas y atención","Citas, formularios y mensajes organizados para que ninguna oportunidad se pierda."],["Operación más simple","Herramientas y automatizaciones que reducen tareas repetitivas dentro de tu negocio."]],serviceLink:"Cuéntame tu idea",industriesKicker:"EXPERIENCIA EN TU MERCADO",industriesTitle:["Una estrategia distinta para","cada tipo de negocio."],industriesIntro:"El mismo objetivo —más confianza y mejores clientes— con una experiencia pensada alrededor de cada servicio.",industries:[["Dentistas y clínicas","Tratamientos, credenciales, ubicación, citas y orientación para pacientes internacionales.","TURISMO MÉDICO"],["Spas y estética","Servicios visuales, paquetes, reservaciones y una presencia que transmite cuidado.","BIENESTAR"],["Salones de belleza","Portafolio, precios, agenda y contenido social para convertir inspiración en citas.","BEAUTY"],["Farmacias y comercios","Información clara, contacto rápido, ubicación y preguntas frecuentes para visitantes.","RETAIL"]],outcomes:["Más confianza antes del viaje","Menos preguntas repetidas","Más citas y contactos calificados"],
    why:"POR QUÉ DEVDEsDECEROMX",whyTitle:["Tu cliente ya está buscando.","Hagamos que te elija."],whyText:"Un turista médico o visitante compara opciones desde Estados Unidos: servicios, ubicación, reseñas y facilidad de contacto. Tu presencia digital debe responder todo eso con claridad.",values:["Comunicación para ambos lados de la frontera.","Diseño que transmite confianza y calidad.","Tecnología sencilla para tu equipo."],statementTop:"LOCAL + BINACIONAL",statementTitle:["Tu negocio está aquí.","Tus clientes pueden estar en cualquier lugar."],statementText:"Construimos el puente digital entre ambos.",
    processKicker:"NUESTRO PROCESO",processTitle:["De la idea al ","impacto."],processIntro:"Un proceso transparente para que siempre sepas qué estamos haciendo, por qué y qué sigue.",steps:[["Entendemos","Conocemos tu negocio, tus clientes y lo que hace especial tu servicio."],["Diseñamos","Creamos una experiencia bilingüe sencilla, útil y con personalidad."],["Construimos","Desarrollamos con tecnología moderna y atención a cada detalle."],["Impulsamos","Publicamos, medimos y mejoramos para generar resultados reales."]],
    contactKicker:"TU PRÓXIMO CLIENTE YA ESTÁ BUSCANDO",contactTitle:["Hagamos que","te encuentre."],contactText:"Cuéntanos sobre tu negocio. La primera conversación es para entenderte, sin compromisos y sin tecnicismos.",contactStrong:"Tu proyecto puede empezar hoy.",email:"También puedes escribirnos a devdesdeceromx@gmail.com",form:{name:"Tu nombre",business:"Negocio",phone:"Teléfono",email:"Correo electrónico",service:"¿Qué necesitas?",message:"Cuéntanos brevemente sobre tu proyecto",send:"Enviar mi idea",sending:"Enviando…",required:"Necesitamos al menos tu correo o teléfono.",success:"¡Recibimos tu mensaje! Te contactaremos muy pronto.",error:"No pudimos enviar tu mensaje. Inténtalo nuevamente.",options:["Sitio web bilingüe","Reservaciones o citas","Sistema a medida","Automatización","Aún no estoy seguro"]},footerText:"Soluciones digitales bilingües para negocios que quieren crecer.",explore:"Explora",follow:"Síguenos",soon:"Muy pronto en redes",made:"Hecho con intención en la frontera 🇲🇽 🇺🇸"
  },
  en: {
    nav:["Services","Process","About us"],talk:"Let's talk",menu:["Open menu","Close menu"],eyebrow:"Technology for border businesses",heroA:"Be found",heroB:"before they cross.",heroText:"We build bilingual digital experiences for Nuevo Progreso businesses serving customers from Mexico and the United States.",start:"Start a project",discover:"See how",proofs:["English + Español","Trust-building design","Local support"],visualLabel:"Representation of a bilingual digital experience",miniTop:"YOUR BUSINESS, WITHOUT BORDERS",miniTitle:["Trust that begins","before the visit."],miniButton:"Book an appointment",performance:"Performance",focus:"Focus",results:"Results",
    servicesKicker:"BUILT FOR LOCAL BUSINESSES",servicesTitle:["Turn searches into","new customers."],servicesIntro:"We help dentists, spas, salons, pharmacies and border businesses look professional, answer questions and make every visit easier.",services:[["Bilingual presence","A clear Spanish and English website that builds trust before your visitor arrives."],["Booking and support","Appointments, forms and messages organized so no opportunity slips away."],["Simpler operations","Tools and automations that reduce repetitive work across your business."]],serviceLink:"Tell me your idea",industriesKicker:"EXPERIENCE IN YOUR MARKET",industriesTitle:["A different strategy for","every kind of business."],industriesIntro:"The same goal—more trust and better customers—with an experience designed around each service.",industries:[["Dentists and clinics","Treatments, credentials, location, booking and guidance for international patients.","MEDICAL TOURISM"],["Spas and aesthetics","Visual services, packages, booking and a presence that communicates care.","WELLNESS"],["Beauty salons","Portfolio, pricing, scheduling and social content that turns inspiration into appointments.","BEAUTY"],["Pharmacies and shops","Clear information, fast contact, location and FAQs for visitors.","RETAIL"]],outcomes:["More trust before the trip","Fewer repetitive questions","More qualified bookings and leads"],
    why:"WHY DEVDEsDECEROMX",whyTitle:["Your customer is already searching.","Let's help them choose you."],whyText:"Medical tourists and visitors compare options from the U.S.: services, location, reviews and how easy it is to reach you. Your digital presence should answer it all, clearly.",values:["Communication for both sides of the border.","Design that conveys trust and quality.","Simple technology for your team."],statementTop:"LOCAL + CROSS-BORDER",statementTitle:["Your business is here.","Your customers can be anywhere."],statementText:"We build the digital bridge between both.",
    processKicker:"OUR PROCESS",processTitle:["From an idea to ","real impact."],processIntro:"A transparent process so you always know what we're doing, why it matters and what comes next.",steps:[["We listen","We learn about your business, customers and what makes your service different."],["We design","We create a simple, useful bilingual experience with personality."],["We build","We develop with modern technology and careful attention to every detail."],["We grow","We launch, measure and improve to generate real results."]],
    contactKicker:"YOUR NEXT CUSTOMER IS ALREADY SEARCHING",contactTitle:["Let's make sure","they find you."],contactText:"Tell us about your business. Our first conversation is about understanding your needs—no pressure and no technical jargon.",contactStrong:"Your project can start today.",email:"You can also email us at devdesdeceromx@gmail.com",form:{name:"Your name",business:"Business name",phone:"Phone",email:"Email address",service:"What do you need?",message:"Tell us briefly about your project",send:"Send my idea",sending:"Sending…",required:"Please provide at least your email or phone.",success:"We got your message! We'll reach out very soon.",error:"We couldn't send your message. Please try again.",options:["Bilingual website","Booking or appointments","Custom system","Automation","I'm not sure yet"]},footerText:"Bilingual digital solutions for businesses ready to grow.",explore:"Explore",follow:"Follow us",soon:"Coming soon on social media",made:"Built with purpose on the border 🇲🇽 🇺🇸"
  }
} as const;

const icons=[Code2,Blocks,Bot];
const industryIcons=[HeartPulse,Sparkles,Scissors,Pill];
const socialItems=[{key:"tiktok",label:"TikTok",icon:Play},{key:"facebook",label:"Facebook",icon:Facebook},{key:"instagram",label:"Instagram",icon:Instagram},{key:"youtube",label:"YouTube",icon:Youtube}] as const;
function Logo({language}:{language:Language}){return <a className="logo" href="#inicio" aria-label={`DevDesdeCeroMx, ${language==="es"?"inicio":"home"}`}><span className="logo-mark"><Blocks size={21}/></span><span><strong>DevDesdeCero</strong><b>Mx</b></span></a>}

export function App(){
  const [menuOpen,setMenuOpen]=useState(false);
  const [language,setLanguage]=useState<Language>(()=>localStorage.getItem("dcx-language")==="en"?"en":"es");
  const [formState,setFormState]=useState<"idle"|"sending"|"success"|"error">("idle");
  const [siteSettings,setSiteSettings]=useState<PublicSiteSettings|null>(null);
  const baseCopy=copy[language];
  const t={...baseCopy,eyebrow:siteSettings?.[`hero_eyebrow_${language}`]??baseCopy.eyebrow,heroA:siteSettings?.[`hero_title_${language}`]??baseCopy.heroA,heroB:siteSettings?.[`hero_highlight_${language}`]??baseCopy.heroB,heroText:siteSettings?.[`hero_description_${language}`]??baseCopy.heroText,email:siteSettings?.contact_email?`${language==="es"?"También puedes escribirnos a":"You can also email us at"} ${siteSettings.contact_email}`:baseCopy.email};
  const socialLinks={tiktok:siteSettings?.tiktok_url??staticSocialLinks.tiktok,facebook:siteSettings?.facebook_url??staticSocialLinks.facebook,instagram:siteSettings?.instagram_url??staticSocialLinks.instagram,youtube:siteSettings?.youtube_url??staticSocialLinks.youtube};
  const activeSocials=socialItems.filter(({key})=>socialLinks[key]);
  useEffect(()=>{localStorage.setItem("dcx-language",language);document.documentElement.lang=language;document.title=language==="es"?"DevDesdeCeroMx · Tu negocio sin fronteras":"DevDesdeCeroMx · Business without borders"},[language]);
  useEffect(()=>{void getPublicSiteSettings().then(({data})=>{if(data)setSiteSettings(data)})},[]);
  async function sendLead(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const data=new FormData(formElement);if(!String(data.get("email")).trim()&&!String(data.get("phone")).trim()){setFormState("error");return}setFormState("sending");const {error}=await submitWebsiteLead({name:String(data.get("name")),businessName:String(data.get("business")),phone:String(data.get("phone")),email:String(data.get("email")),service:String(data.get("service")),message:String(data.get("message")),language,website:String(data.get("website"))});if(error){setFormState("error");return}formElement.reset();setFormState("success")}
  return <div className="site-shell" data-services={siteSettings?.show_services??true} data-industries={siteSettings?.show_industries??true} data-about={siteSettings?.show_about??true} data-process={siteSettings?.show_process??true}>
    <header className="site-header"><Logo language={language}/><nav className={menuOpen?"nav-open":""} aria-label={language==="es"?"Navegación principal":"Main navigation"}><a href="#servicios" onClick={()=>setMenuOpen(false)}>{t.nav[0]}</a><a href="#proceso" onClick={()=>setMenuOpen(false)}>{t.nav[1]}</a><a href="#nosotros" onClick={()=>setMenuOpen(false)}>{t.nav[2]}</a><button className="language-switch" onClick={()=>setLanguage(language==="es"?"en":"es")} aria-label={language==="es"?"View in English":"Ver en español"}><Globe2 size={15}/><b>{language.toUpperCase()}</b><span>/</span>{language==="es"?"EN":"ES"}</button><a href="#contacto" className="nav-cta" onClick={()=>setMenuOpen(false)}>{t.talk}<ArrowRight size={15}/></a></nav><button className="menu-button" onClick={()=>setMenuOpen(!menuOpen)} aria-label={menuOpen?t.menu[1]:t.menu[0]}>{menuOpen?<X/>:<Menu/>}</button></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-glow"/><div className="hero-copy"><span className="eyebrow"><i/>{t.eyebrow}</span><h1>{t.heroA}<br/><em>{t.heroB}</em></h1><p>{t.heroText}</p><div className="hero-actions"><a className="button primary" href="#contacto">{t.start}<ArrowRight size={18}/></a><a className="button ghost" href="#servicios"><Play size={15} fill="currentColor"/>{t.discover}</a></div><div className="hero-proof">{t.proofs.map(item=><span key={item}><Check size={14}/>{item}</span>)}</div></div>
        <div className="hero-visual" aria-label={t.visualLabel}><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="code-card"><div className="window-bar"><span/><span/><span/><small>devdesdeceromx.dev</small></div><div className="code-body"><div className="mini-sidebar"><b>DCX</b><i/><i/><i/></div><div className="mini-content"><span>{t.miniTop}</span><strong>{t.miniTitle[0]}<br/>{t.miniTitle[1]}</strong><div className="mini-button">{t.miniButton}</div><div className="mini-grid"><i/><i/><i/></div></div></div></div><div className="float-card float-top"><span><Zap size={16}/></span><div><small>{t.performance}</small><strong>98/100</strong></div></div><div className="float-card float-bottom"><span><Target size={16}/></span><div><small>{t.focus}</small><strong>{t.results}</strong></div></div></div><div className="scroll-cue">SCROLL <i/></div></section>
      <section className="section services" id="servicios"><div className="section-heading"><div><span className="kicker">{t.servicesKicker}</span><h2>{t.servicesTitle[0]}<br/><em>{t.servicesTitle[1]}</em></h2></div><p>{t.servicesIntro}</p></div><div className="service-grid">{t.services.map(([title,text],index)=>{const Icon=icons[index];return <article className="service-card" key={title}><div className="service-top"><span><Icon/></span><small>0{index+1}</small></div><h3>{title}</h3><p>{text}</p><a href="#contacto">{t.serviceLink}<ChevronRight size={15}/></a></article>})}</div></section>
      <section className="industries"><div className="industries-intro"><span className="kicker light">{t.industriesKicker}</span><h2>{t.industriesTitle[0]}<br/><em>{t.industriesTitle[1]}</em></h2><p>{t.industriesIntro}</p><div className="outcome-list">{t.outcomes.map(item=><span key={item}><Check size={15}/>{item}</span>)}</div></div><div className="industry-grid">{t.industries.map(([title,text,tag],index)=>{const Icon=industryIcons[index];return <article key={title}><div><span><Icon size={19}/></span><small>{tag}</small></div><h3>{title}</h3><p>{text}</p><a href="#contacto" aria-label={`${t.serviceLink}: ${title}`}><ArrowRight size={17}/></a></article>})}</div></section>
      <section className="dark-section" id="nosotros"><div className="manifesto"><span className="kicker light">{t.why}</span><h2>{t.whyTitle[0]}<br/><em>{t.whyTitle[1]}</em></h2><p>{t.whyText}</p><div className="values">{t.values.map((item,index)=><div key={item}><strong>0{index+1}.</strong><span>{item}</span></div>)}</div></div><div className="statement-card"><Sparkles/><span>{t.statementTop}</span><strong>{t.statementTitle[0]}<br/>{t.statementTitle[1]}</strong><p>{t.statementText}</p></div></section>
      <section className="section process" id="proceso"><div className="section-heading"><div><span className="kicker">{t.processKicker}</span><h2>{t.processTitle[0]}<em>{t.processTitle[1]}</em></h2></div><p>{t.processIntro}</p></div><div className="process-list">{t.steps.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p><ArrowRight/></article>)}</div></section>
      <section className="contact" id="contacto"><div className="contact-orb"/><div className="contact-copy"><span className="kicker light">{t.contactKicker}</span><h2>{t.contactTitle[0]}<br/><em>{t.contactTitle[1]}</em></h2><p>{t.contactText}</p><div className="contact-note"><Rocket/><div><strong>{t.contactStrong}</strong><span>{t.email}</span></div></div></div><form className="lead-form" onSubmit={sendLead}><div className="lead-form-grid"><label>{t.form.name}<input name="name" minLength={2} maxLength={80} required/></label><label>{t.form.business}<input name="business" maxLength={120}/></label><label>{t.form.phone}<input name="phone" type="tel" maxLength={30}/></label><label>{t.form.email}<input name="email" type="email" maxLength={160}/></label></div><label>{t.form.service}<select name="service" required defaultValue=""><option value="" disabled>—</option>{t.form.options.map(option=><option key={option}>{option}</option>)}</select></label><label>{t.form.message}<textarea name="message" rows={3} maxLength={1500}/></label><label className="website-field" aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label>{formState==="success"&&<p className="lead-success"><CheckCircle2 size={17}/>{t.form.success}</p>}{formState==="error"&&<p className="lead-error">{t.form.error} {t.form.required}</p>}<button className="lead-submit" disabled={formState==="sending"}>{formState==="sending"?<LoaderCircle className="spin" size={18}/>:<Send size={18}/>} {formState==="sending"?t.form.sending:t.form.send}</button></form></section>
    </main>
    <footer><div><Logo language={language}/><p>{t.footerText}</p></div><div className="footer-links"><strong>{t.explore}</strong><a href="#servicios">{t.nav[0]}</a><a href="#proceso">{t.nav[1]}</a><a href="#nosotros">{t.nav[2]}</a></div><div className="footer-social"><strong>{t.follow}</strong>{activeSocials.length?<div>{activeSocials.map(({key,label,icon:Icon})=><a href={socialLinks[key]} key={key} target="_blank" rel="noreferrer" aria-label={label}><Icon size={18}/></a>)}</div>:<span>{t.soon}</span>}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} DevDesdeCeroMx</span><span>{t.made}</span></div></footer>
  </div>
}
